version: '3.6'
services:
    postgresql:
        image: postgres:9
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: ./postgresql/data