version: '3.6'
services:
    postgresql:
        image: postgres:9
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: postgresql/data
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 5432:5432